spring:
  application:
    name: drug-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: ${aliyun.dashscope.api-key}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3

server:
  port: 8124
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liang.drugagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

# 阿里云百炼(DashScope) 千问模型配置
aliyun:
  dashscope:
    api-key: ${DASHscope_API_KEY:} # 优先从环境变量读取，本地开发则由 application-local.yml 覆盖
